#!/usr/bin/env python3
import json, hashlib, collections
sha = lambda p: hashlib.sha256(open(p,'rb').read()).hexdigest()

m = json.load(open('phase15_manifest.json'), object_pairs_hook=collections.OrderedDict)

CANON = 'trader_v2/V53_ltf_sequence.pine'
EXEC  = 'trader_v2/p15/executed/V53_EXECUTED_BUILD.pine'

old_baseline = m['baseline']
m['provenance_correction'] = collections.OrderedDict([
 ("raised", "Phase 15, at the start of Experiment C1, after Experiment B completed"),
 ("record", "trader_v2/p15/PHASE15_PROVENANCE_CORRECTION.md"),
 ("hard_stop_record", "trader_v2/p15/PHASE15_HARD_STOP.md"),
 ("summary", "The initial manifest identified V53_ltf_sequence.pine as the execution baseline. "
             "An audit during Experiment B preparation established that TradingView had actually been "
             "executing the artifact now preserved at p15/executed/V53_EXECUTED_BUILD.pine. The two were "
             "compared and found to have identical strategy-bearing logic, differing only in write-only "
             "diagnostics and the output layer."),
 ("canonical_source", collections.OrderedDict([
    ("file", CANON),
    ("sha256", sha('../V53_ltf_sequence.pine')),
    ("role", "canonical frozen V53 source; Phase 13E audited it; NOT the artifact that executed"),
    ("status", "unmodified and to remain unmodified"),
 ])),
 ("executed_baseline", collections.OrderedDict([
    ("file", EXEC),
    ("sha256", sha('executed/V53_EXECUTED_BUILD.pine')),
    ("lines", 602),
    ("role", "the actual TradingView artifact that produced all Phase 15 measurements; "
             "provenance anchor for the whole phase"),
    ("captured_via", "pine_get_source on study USER;b798deb2c9084500a1c38b14775961da version 137.0"),
    ("capture_integrity", "reported 602 lines / 27,240 chars; captured file is 602 lines / 27,241 bytes "
                          "(difference is the trailing newline)"),
 ])),
 ("equivalence_verification", collections.OrderedDict([
    ("method", "strategy sections 1-6 of both files extracted (everything before the line "
               "'g(i) => str.tostring(array.get(K, i))'), comments and blank lines stripped, then diffed"),
    ("strategy_bearing_lines_identical", True),
    ("differences_found", [
       "writes to K33 and K34 in the section 6 detector-verification block",
       "writes to K35 in the same block",
       "the `tie` boolean local and the loop that sets it, which exists only to gate K35",
    ]),
    ("difference_classification", "write-only diagnostics. K33, K34, K35 and `tie` are never read by any "
                                  "decision in the program; the canonical build only displays them as table "
                                  "rows D33/D34/D35. They cannot affect strategy behaviour."),
    ("also_identical", ["all 15 inputs, in the same order, so the in_0..in_14 mapping is preserved",
                        "5m sweep engine", "LTF pivot detector", "CHOCH", "CHOCH retest (zero tolerance)",
                        "BOS + displacement with CHOCH-pivot exclusion", "FVG selection",
                        "fill and R-band test", "outcome model", "arm block",
                        "SP, RB, and the fold boundaries FB/FC/FE"]),
    ("other_differences", "comments, and the section 7 output layer (table structure and ledger header)"),
    ("behavioural_equivalence_established", True),
 ])),
 ("A_B_provenance", "Experiments A and B were generated by the executed V53 artifact "
                    "(p15/executed/V53_EXECUTED_BUILD.pine), not directly by V53_ltf_sequence.pine."),
 ("A_B_validity", "Experiments A and B remain valid because the executed artifact's strategy-bearing logic "
                  "is identical to the canonical V53, and the intended experimental input was the only "
                  "strategy-bearing change between arms. They are NOT rerun and their recorded results are "
                  "preserved unchanged."),
 ("C_to_G_provenance", "Experiments C1-G1 are generated from the actual executed baseline artifact, with "
                       "exactly one predefined strategy-bearing modification per arm. The executed build's "
                       "diagnostic and output layers are carried through byte-identical."),
 ("superseded_artifacts", collections.OrderedDict([
    ("files", ["trader_v2/p15/V53_P15_C1_retest_tol.pine",
               "trader_v2/p15/V53_P15_D1_bos_include.pine",
               "trader_v2/p15/V53_P15_E1_fvg_forward.pine",
               "trader_v2/p15/V53_P15_F1_raw_stop.pine",
               "trader_v2/p15/V53_P15_G1_first_choch.pine"]),
    ("status", "SUPERSEDED AND NEVER EXECUTED"),
    ("reason", "derived from the canonical source rather than the executed artifact; retained as "
               "historical evidence, not deleted"),
 ])),
])

m['baseline_original_entry_retained_for_history'] = old_baseline
m['baseline'] = collections.OrderedDict([
 ("commit_head", old_baseline.get("commit_head")),
 ("v53_last_modified_commit", old_baseline.get("v53_last_modified_commit")),
 ("execution_baseline_file", EXEC),
 ("execution_baseline_sha256", sha('executed/V53_EXECUTED_BUILD.pine')),
 ("canonical_source_file", CANON),
 ("canonical_source_sha256", sha('../V53_ltf_sequence.pine')),
 ("note", "execution_baseline_* is the provenance anchor. canonical_source_* is the frozen reference "
          "source; it did not execute. See provenance_correction."),
 ("results", old_baseline.get("results")),
])

DERIVED = {
 "C1": ("trader_v2/p15/exec_arms/V53_EXEC_P15_C1_retest_tol.pine",       "exec_arms/V53_EXEC_P15_C1_retest_tol.pine",       "2 sites, +5/-1 lines"),
 "D1": ("trader_v2/p15/exec_arms/V53_EXEC_P15_D1_bos_reference.pine",    "exec_arms/V53_EXEC_P15_D1_bos_reference.pine",    "2 hunks, +2/-4 lines"),
 "E1": ("trader_v2/p15/exec_arms/V53_EXEC_P15_E1_fvg_association.pine",  "exec_arms/V53_EXEC_P15_E1_fvg_association.pine",  "2 sites, +7/-4 lines"),
 "F1": ("trader_v2/p15/exec_arms/V53_EXEC_P15_F1_stop_raw_extreme.pine", "exec_arms/V53_EXEC_P15_F1_stop_raw_extreme.pine", "1 line"),
 "G1": ("trader_v2/p15/exec_arms/V53_EXEC_P15_G1_first_choch_pivot.pine","exec_arms/V53_EXEC_P15_G1_first_choch_pivot.pine","6 hunks, +14/-8 lines"),
}

for e in m['experiments']:
    eid = e['id']
    if eid in ('A', 'B'):
        e['executed_against'] = EXEC
        e['executed_against_sha256'] = sha('executed/V53_EXECUTED_BUILD.pine')
        e['code_change'] = "NONE - file byte-identical to the EXECUTED baseline; only an input varies"
        e['sha256'] = sha('executed/V53_EXECUTED_BUILD.pine')
        e['file'] = EXEC
        e['status'] = "COMPLETE - not rerun under the provenance correction; results preserved unchanged"
        e['provenance_note'] = ("originally recorded against " + CANON + " (sha256 " +
                                sha('../V53_ltf_sequence.pine') + "); corrected to the executed artifact")
    else:
        path, local, chg = DERIVED[eid]
        e['superseded_file'] = e['file']
        e['superseded_sha256'] = e['sha256']
        e['superseded_status'] = "NEVER EXECUTED - derived from the canonical source, retained as history"
        e['file'] = path
        e['sha256'] = sha(local)
        e['derived_from'] = EXEC
        e['derived_from_sha256'] = sha('executed/V53_EXECUTED_BUILD.pine')
        e['code_change'] = chg + " against the executed baseline"
        e['output_layer'] = "byte-identical to the executed baseline (verified)"
        e['single_concept_verification'] = "trader_v2/p15/exec_arms/SINGLE_CONCEPT_VERIFICATION.txt"
        e['status'] = "PENDING"

json.dump(m, open('phase15_manifest.json','w'), indent=1)
open('phase15_manifest.json','a').write('\n')
print("manifest updated")
for e in m['experiments']:
    print(f"  {e['id']:3s} {e['status']:12s} {e['sha256'][:16]}  {e['file']}")
